### ISSUE TITLE
Unauthorized error

### ISSUE THREAD

**Issue by djkapur** [sreedharande/MS-Sentinel-Bulk-Delete-Threat-Indicators#1]
We are trying to delete IOCs (count is ~500k) using the script, but it is giving unauthorized error after deleting some indicators.

<img width="599" alt="Error" src="https://user-images.githubusercontent.com/113426281/190717605-fce05791-43b3-4e73-b8ff-438ff06ebd93.png">

**Comment by sreedharande** [comment]
@djkapur - this is fixed now
